[package]
name = "gameforge-bootstrap"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
gameforge-event-journal = { path = "../event-journal" }
gameforge-persistence = { path = "../persistence" }
gameforge-project-documents = { path = "../project-documents" }
gameforge-runtime = { path = "../runtime" }

[lints]
workspace = true

